name: iOSVideoPlayer
options:
  bundleIdPrefix: com.vibrantborg
targets:
  iOSVideoPlayer:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - iOSVideoPlayer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibrantborg.iosvideoplayer
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: iOSVideoPlayer/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        AD_HOC_CODE_SIGNING_ALLOWED: YES
