name: iOSVideoPlayer
options:
  bundleIdPrefix: com.vibrantborg
packages:
  Swifter:
    url: https://github.com/httpswift/swifter.git
    from: 1.5.0
targets:
  iOSVideoPlayer:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - iOSVideoPlayer
    settings:
      INFOPLIST_FILE: iOSVideoPlayer/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.vibrantborg.iosvideoplayer
      TARGETED_DEVICE_FAMILY: "1,2"
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
    dependencies:
      - package: Swifter
